background: center / cover no-repeat fixed  url('/local/images/bg_long.png?v=1')
custom_header:
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        hide_header: true
    - conditions:
        user_agent: Android
      config:
        hide_header: true
views:
  - icon: mdi:mdi-home-automation
    name: Automations
    path: automations
    panel: true
    badges: []
    cards:
    - type: vertical-stack
      cards:
      - type: 'custom:button-card'
        size: 25px
        icon: 'mdi:close'
        tap_action:
          action: navigate
          navigation_path: /
        styles:
          card:
            - width: 40px
            - height: 40px
            - background-color: 'rgba(255,255,255,0)'
            - box-shadow: none
            - margin-bottom: '-25px'
          icon:
            - margin-left: px
      - type: "custom:homekit-card"
        style: !include /config/lovelace/homekit/styles.yaml
        home: false
        title: Home
        useBrightness: true
        useTemperature: true
        titleColor: '#FFF'
        statePositionTop: false
        entities:
        - title: Automation Mode
          entities:
          - entity: binary_sensor.automation_home_mode
            name: Home
            icon: mdi:home
            tap_action:
              haptic: heavy
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.automation_mode
                option: home
          - entity: binary_sensor.automation_away_mode
            name: Away
            icon: mdi:exit-run
            tap_action:
              haptic: heavy
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.automation_mode
                option: away
          - entity: binary_sensor.automation_sleep_mode
            name: Sleep
            icon: mdi:weather-night
            tap_action:
              haptic: heavy
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.automation_mode
                option: sleep
          - entity: binary_sensor.automation_guest_mode
            name: Guest
            icon: mdi:human-male-male
            tap_action:
              haptic: heavy
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.automation_mode
                option: guest
          - entity: binary_sensor.automation_vacation_mode
            name: Vacation
            icon: mdi:beach
            tap_action:
              haptic: heavy
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.automation_mode
                option: vacation
        - title: Automations
          entities:
          - entity: switch.chill_mode
            name: Wind Down
            icon: mdi:meditation
            tap_action:
              haptic: heavy
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.chill_mode
          - entity: switch.night_shift
            name: Night Shift
            icon: mdi:stethoscope
            tap_action:
              haptic: heavy
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.night_shift
