background: center / cover no-repeat fixed  url('/local/images/bg_long.png?v=1')
custom_header:
  exceptions:
    - conditions:
        user_agent: Android
      config:
        hide_header: true
    - conditions:
        user_agent: Mobile
      config:
        hide_header: true
views:
  - icon: mdi:camera-burst
    name: Cameras
    path: cameras
    panel: true
    cards:
    - type: vertical-stack
      cards:
      - type: 'custom:button-card'
        size: 25px
        icon: 'mdi:close'
        tap_action:
          action: navigate
          navigation_path: /
        styles:
          card:
            - width: 40px
            - height: 40px
            - background-color: 'rgba(255,255,255,0)'
            - box-shadow: none
            - margin-bottom: '0px'
          icon:
            - margin-left: px
      - type: iframe
        url: !secret driveway_480p_url
        aspect_ratio: '16:9'
        card_mod:
          style: |
            ha-card {
              margin: 0 20px;
            }