default_config:

system_log:
  
lovelace:
  mode: yaml

homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Chicago
  name: Home
  customize: !include customize.yaml
  packages:  !include_dir_named packages

binary_sensor:
- platform: ping
  host: google.com
  count: 2
  scan_interval: 30
  name: google
- platform: ping
  host: 192.168.1.22
  count: 2
  scan_interval: 30
  name: Work Laptop
- platform: ping
  host: 192.168.1.23
  count: 2
  scan_interval: 30
  name: Desktop PC
- platform: ping
  host: 192.168.1.100
  count: 2
  scan_interval: 30
  name: Diskstation
- platform: ping
  host: 192.168.1.31
  count: 2
  scan_interval: 30
  name: Mini PC

device_tracker:
- platform: netgear
  host: 192.168.1.1
  port: 5000
  username: !secret router_username
  password: !secret router_password

customizer:
  custom_ui: local

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

notify:
  - platform: html5
    name: HTML5 Notifications
    vapid_pub_key: !secret notify_html5_vapid_public_key
    vapid_prv_key: !secret notify_html5_vapid_private_key
    vapid_email: !secret email_address

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml

media_player:
  - platform: braviatv_psk
    host: 192.168.1.20
    psk: 3813
    mac: 0C:96:E6:A6:67:B3
    amp: True
    android: True
    name: Living Room TV
  - platform: denonavr
    host: 192.168.1.15
    name: Living Room Receiver
    show_all_sources: true

switch: !include switches.yaml

frontend:
  themes: !include themes.yaml
  
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sensor: !include sensors.yaml

weather:
- platform: darksky
  api_key: !secret darksky_api_key

api:

alexa:
  smart_home:
    filter:
      include_entities:
      - group.kitchen_lights
      - switch.bar_lights
      - switch.cabinet_lights
      - switch.ikea_outlet_3
      - light.living_room_lights

      - cover.garage_door

      - climate.thermostat

      - script.vacuum_start_cleanup
      - script.vacuum_pause_cleanup
      - script.vacuum_resume_cleanup
      - script.vacuum_stop_cleanup
      - script.vacuum_return_to_dock
      - script.vacuum_go_to_trash_can
    entity_config:
      group.kitchen_lights:
        name: Kitchen Lights
        description: All of the lights in the kitchen
        display_categories: SWITCH
      switch.bar_lights:
        name: Bar Lights
        description: Lighting over the bar in the kitchen
        display_categories: SWITCH
      switch.cabinet_lights:
        name: Cabinet Lights
        description: Lighting attached to the kitchen cabinets
        display_categories: SWITCH
      switch.ikea_outlet_3:
        name: Ledge Lights
        description: Ledge lighting in the great room
        display_categories: SWITCH
      light.living_room_lights:
        name: Living Room Lights
        description: Lighting in the living room area
        display_categories: LIGHT
      cover.garage_door:
        name: Garage Door
        description: Open or close the garage
        display_categories: DOOR
      climate.thermostat:
        name: Thermostat
        description: Set the desired temperature
      script.vacuum_start_cleanup:
        name: Script - Vacuum Start Cleanup
        description: Start cleaning the house
      script.vacuum_pause_cleanup:
        name: Script - Vacuum Pause Cleanup in progress
        description: Pause the cleanup in progress
      script.vacuum_resume_cleanup:
        name: Script - Vacuum Resume Cleanup in progress
        description: Resume the cleanup in progress
      script.vacuum_stop_cleanup:
        name: Script - Vacuum Stop Cleanup
        description: Stop the cleanup in progress
      script.vacuum_return_to_dock:
        name: Script - Vacuum Return to Dock
        description: Go back to the dock
      script.vacuum_go_to_trash_can:
        name: Script - Vacuum Go To Trash Can
        description: Send vacuum to the trash can


zone:
- name: !secret grocery_store_1_name
  latitude: !secret grocery_store_1_latitude
  longitude: !secret grocery_store_1_longitude
  icon: mdi:store
- name: !secret wholesale_store_1_name
  latitude: !secret wholesale_store_1_latitude
  longitude: !secret wholesale_store_1_longitude
  icon: mdi:store

python_script:
