background: center / cover no-repeat fixed  url('/local/images/bg_long.png?v=1')
custom_header:
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        hide_header: true
    - conditions:
        user_agent: Android
      config:
        hide_header: true
views:
  - icon: mdi:doorbell-video
    name: Doorbell
    path: doorbell
    panel: true
    badges: []
    cards:
    - type: vertical-stack
      cards:
      - type: 'custom:button-card'
        size: 25px
        icon: 'mdi:close'
        tap_action:
          action: navigate
          navigation_path: /
        styles:
          card:
            - width: 40px
            - height: 40px
            - background-color: 'rgba(255,255,255,0)'
            - box-shadow: none
          icon:
            - margin-left: px
      - type: markdown
        content: '### Doorbell Live View'
        style: |
          ha-card {
            margin-bottom: -7px;
            background: rgba(255, 255, 255, 0.0);
            border-radius: 0px;
            box-shadow: none;
            color: white; 
            font-family: Arial;
          }
      - type: iframe
        url: !secret doorbell_480p_url
        aspect_ratio: '16:9'
          

      - type: markdown
        content: '### Latest Motion Trigger'
        style: |
          ha-card {
            margin-bottom: -7px;
            background: rgba(255, 255, 255, 0.0);
            border-radius: 0px;
            box-shadow: none;
            color: white; 
            font-family: Arial;
          }
      - type: picture-entity
        entity: camera.doorbell_person_alert_latest
        camera_view: live
        show_name: false
        show_state: false
          

      - type: markdown
        content: '### Latest Doorbell Press'
        style: |
          ha-card {
            margin-bottom: -7px;
            background: rgba(255, 255, 255, 0.0);
            border-radius: 0px;
            box-shadow: none;
            color: white; 
            font-family: Arial;
          }
      - type: picture-entity
        entity: camera.doorbell_press_alert_latest
        camera_view: live
        show_name: false
        show_state: false
  - icon: mdi:doorbell-video
    name: Doorbell
    path: doorbell
    panel: true
    badges: []
    cards:
    - type: vertical-stack
      cards:
      - type: 'custom:button-card'
        size: 25px
        icon: 'mdi:close'
        tap_action:
          action: navigate
          navigation_path: /
        styles:
          card:
            - width: 40px
            - height: 40px
            - background-color: 'rgba(255,255,255,0)'
            - box-shadow: none
          icon:
            - margin-left: px
      - type: iframe
        url: !secret doorbell_480p_url
        aspect_ratio: '16:9'
        card_mod:
          style: |
            ha-card {
              margin: 0 20px;
            }