background: center / cover no-repeat fixed  url('/local/images/bg_long.png?v=1')
custom_header:
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        hide_header: true
views:
  - icon: mdi:doorbell-video
    name: Doorbell
    path: doorbell
    badges: []
    cards:
    - type: vertical-stack
      cards:
      - type: 'custom:button-card'
        size: 25px
        icon: 'mdi:close'
        tap_action:
          action: navigate
          navigation_path: /mobile-dashboard/0
        styles:
          card:
            - width: 40px
            - height: 40px
            - background-color: 'rgba(255,255,255,0)'
            - box-shadow: none
            - margin-bottom: '-25px'
          icon:
            - margin-left: px
      - type: markdown
        content: Latest Doorbell Alert
        card_mod:
          style: |
            ha-card {
              background: rgba(255,255,255,0) !important;
              box-shadow: none;
              margin-bottom: 0;
              font-family: Arial;
              font-size: 16px;
              font-weight: bold;
            }
            ha-markdown {
              margin-top: 30px;
              padding: 0px!important;
            }
      - type: picture-entity
        entity: camera.doorbell_person_alert_latest
        camera_view: live
        show_name: false
        show_state: false
      - type: markdown
        content: Doorbell Live View
        card_mod:
          style: |
            ha-card {
              background: rgba(255,255,255,0) !important;
              box-shadow: none;
              margin-bottom: 0;
              font-family: Arial;
              font-size: 16px;
              font-weight: bold;
            }
            ha-markdown {
              margin-top: 20px;
              padding: 0px!important;
            }
      - type: iframe
        url: !secret doorbell_480p_url
        aspect_ratio: '16:9'