- platform: group
  name: Living Room Lights
  entities:
    - light.couch_lamp
    - light.love_seat_lamp
    - light.living_room_ambience_1
    - light.living_room_ambience_2
- platform: group
  name: Guest Room Lights
  entities:
    - light.guest_room_lamp_1
    - light.guest_room_lamp_2
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.kp_bedside
    - light.andrew_bedside
- platform: group
  name: Man-cave Lights
  entities:
    - light.man_cave
    - light.man_cave_dimmable
- platform: group
  name: Laundry Room Lights
  entities:
    - light.laundry_room_light_1
    - light.laundry_room_light_2
- platform: group
  name: Driveway Lights
  entities:
  - light.driveway_light_1
  - light.driveway_light_2