background: center / cover no-repeat fixed  url('/local/images/bg_long.png?v=1')
title: Man-cave Tablet
custom_header:
  exceptions:
    - conditions:
        user_agent: Android
      config:
        hide_header: true
    - conditions:
        user_agent: Mobile
      config:
        hide_header: true
views:
- title: Home
  panel: true
  badges: []
  cards:
  - type: custom:hui-horizontal-stack-card
    cards:
    - type: custom:hui-vertical-stack-card
      cards:
      - type: custom:hui-vertical-stack-card
        cards:
        - type: "custom:homekit-card"
          style: !include /config/lovelace/homekit/styles.yaml
          home: false
          titleColor: '#FFF'
          entities:
          - title: Home Assistant
            entities:
            - card: iframe
              conditionalClass: |
                [[[ 
                  return "camera-iframe";
                ]]]
              entity: sensor.always_off
              offStates:
              - "off"
              cardOptions:
                url: !secret driveway_480p_url
                aspect_ratio: '16:9'
              noPadding: true
              wider: true
              widerSize: 5
      - !include /config/lovelace/homekit/man-cave-tablet-favorites.yaml
    - type: custom:hui-vertical-stack-card
      cards:
      - !include /config/lovelace/homekit/dashboard.yaml