title: Man-cave Tablet
custom_header:
  compact_mode: true
views:
- !include /config/lovelace/views/man-cave-tablet/home.yaml
- !include /config/lovelace/views/shared/rooms.yaml
- !include /config/lovelace/views/shared/climate.yaml
- !include /config/lovelace/views/shared/meal-plan.yaml
- !include /config/lovelace/views/shared/network.yaml
- !include /config/lovelace/views/shared/security.yaml
- !include /config/lovelace/views/shared/system-monitor.yaml