background: center / cover no-repeat fixed  url('/local/images/bg_long.png?v=1')
custom_header:
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        hide_header: true
views:
  - icon: mdi:cast
    name: Media Players
    path: media-players
    badges: []
    cards:
    - type: vertical-stack
      cards:
      - type: 'custom:button-card'
        size: 25px
        icon: 'mdi:close'
        tap_action:
          action: navigate
          navigation_path: /mobile-dashboard/0
        styles:
          card:
            - width: 40px
            - height: 40px
            - background-color: 'rgba(255,255,255,0)'
            - box-shadow: none
            # - margin-bottom: '-25px'
          icon:
            - margin-left: px

      - type: custom:mini-media-player
        entity: media_player.living_room_tv
        artwork: cover