- platform: time_date
  display_options:
  - 'time'
  - 'date'
  - 'date_time'
  - 'date_time_iso'
  - 'time_date'
  - 'time_utc'
  - 'beat'
  
- platform: template
  sensors:
    temperature_6_calibrated:
      friendly_name: 'Laundry Room Temperature'
      value_template: '{{ states.sensor.temperature_6.state | float + 2.5 }}'
      unit_of_measurement: 'degrees'

    anybody_home:
      friendly_name: 'Anybody Home'
      value_template: '{{ states("person.andrew") == "home" or  states("person.kaitlyn") == "home" }}'