- platform: time_date
  display_options:
  - 'time'
  - 'date'
  - 'date_time'
  - 'date_time_iso'
  - 'time_date'
  - 'time_utc'
  - 'beat'
  
- platform: template
  sensors:
    thermostat_weather_temp:
      friendly_name: 'Thermostat Outdoor Temp'
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('weather.thermostat', 'temperature') }}"
    front_door_open_close:
      friendly_name: 'Front Door Open/Close'
      value_template: >
        {% if is_state('binary_sensor.openclose_2', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.openclose_2', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door
        {% endif %}
    garage_open_close:
      friendly_name: 'Garage Open/Close'
      value_template: >
        {% if is_state('binary_sensor.openclose_12', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.openclose_12', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
    man_cave_door_open_close:
      friendly_name: 'Man Cave Door Open/Close'
      value_template: >
        {% if is_state('binary_sensor.openclose_15', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.openclose_15', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door
        {% endif %}

    temperature_6_calibrated:
      friendly_name: 'Laundry Room Temperature'
      value_template: '{{ states.sensor.temperature_6.state | float + 2.5 }}'
      unit_of_measurement: 'degrees'

    anybody_home:
      friendly_name: 'Anybody Home'
      value_template: '{{ states("person.andrew") == "home" or  states("person.kaitlyn") == "home" }}'