- platform: time_date
  display_options:
  - 'time'
  - 'date'
  - 'date_time'
  - 'date_time_iso'
  - 'time_date'
  - 'time_utc'
  - 'beat'

- platform: rest
  name: Lenovo Tablet 1001 Kiosk Device Info
  resource: !secret rest_url_lenovo_tablet_1001_kiosk_device_info
  json_attributes:
  - screenBrightness
  - currentPage
  - ip4
  - mac
  - screenOn
  - batteryLevel
  - deviceID
  - maintenanceMode
  - deviceManufacturer
  - deviceModel
  - isInScreensaver
  value_template: 'OK'

- platform: rest
  name: Samsung Tablet 1001 Kiosk Device Info
  resource: !secret rest_url_samsung_tablet_1001_kiosk_device_info
  json_attributes:
  - screenBrightness
  - currentPage
  - ip4
  - mac
  - screenOn
  - batteryLevel
  - deviceID
  - maintenanceMode
  - deviceManufacturer
  - deviceModel
  value_template: 'OK'

- platform: rest
  name: Samsung Tablet 1002 Kiosk Device Info
  resource: !secret rest_url_samsung_tablet_1002_kiosk_device_info
  json_attributes:
  - screenBrightness
  - currentPage
  - ip4
  - mac
  - screenOn
  - batteryLevel
  - deviceID
  - maintenanceMode
  - deviceManufacturer
  - deviceModel
  value_template: 'OK'

- platform: rest
  name: Lenovo Tablet 701 Kiosk Device Info
  resource: !secret rest_url_lenovo_tablet_701_kiosk_device_info
  json_attributes:
  - screenBrightness
  - currentPage
  - ip4
  - mac
  - screenOn
  - batteryLevel
  - deviceID
  - maintenanceMode
  - deviceManufacturer
  - deviceModel
  value_template: 'OK'

- platform: rest
  name: Fire Tablet 701 Kiosk Device Info
  resource: !secret rest_url_fire_tablet_701_kiosk_device_info
  json_attributes:
  - screenBrightness
  - currentPage
  - ip4
  - mac
  - screenOn
  - batteryLevel
  - deviceID
  - maintenanceMode
  - deviceManufacturer
  - deviceModel
  value_template: 'OK'

- platform: rest
  name: Last Watch AI Alive
  resource: !secret last_watch_alive
  value_template: 'OK'

- platform: template
  sensors:
    is_weekday:
      value_template: '{{ now().weekday() < 5 }}'
    month:
      value_template: >
        {% if (now().month == 1) %}
          January
        {% elif (now().month == 2) %}
          February
        {% elif (now().month == 3) %}
          March
        {% elif (now().month == 4) %}
          April
        {% elif (now().month == 5) %}
          May
        {% elif (now().month == 6) %}
          June
        {% elif (now().month == 7) %}
          July
        {% elif (now().month == 8) %}
          August
        {% elif (now().month == 9) %}
          September
        {% elif (now().month == 10) %}
          October
        {% elif (now().month == 11) %}
          November
        {% elif (now().month == 12) %}
          December
        {% endif %}
    month_abbr:
      value_template: >
        {% if (now().month == 1) %}
          JAN
        {% elif (now().month == 2) %}
          FEB
        {% elif (now().month == 3) %}
          MAR
        {% elif (now().month == 4) %}
          APR
        {% elif (now().month == 5) %}
          MAY
        {% elif (now().month == 6) %}
          JUN
        {% elif (now().month == 7) %}
          JUL
        {% elif (now().month == 8) %}
          AUG
        {% elif (now().month == 9) %}
          SEP
        {% elif (now().month == 10) %}
          OCT
        {% elif (now().month == 11) %}
          NOV
        {% elif (now().month == 12) %}
          DEC
        {% endif %}

    date_abbr:
      value_template: >
        {{ states.sensor.month_abbr.state + " " + (now().day | string) }}

    hvac_mode:
      value_template: '{{ state_attr("climate.thermostat", "hvac_action") }}'

