- platform: xiaomi_miio
  host: 192.168.1.27
  token: !secret xiaomi_outlet_1_token
  name: Power Outlet 1
- platform: xiaomi_miio
  host: 192.168.1.29
  token: !secret xiaomi_outlet_2_token
  name: Power Outlet 2

- platform: template
  switches:
    all_lights_off:
      value_template: "{{ True }}"
      turn_on:
      turn_off:
      - service: script.all_lights_off