- platform: xiaomi_miio
  host: 192.168.1.27
  token: !secret xiaomi_outlet_1_token
  name: Power Outlet 1
  scan_interval: 10
- platform: xiaomi_miio
  host: 192.168.1.29
  token: !secret xiaomi_outlet_2_token
  name: Power Outlet 2
  scan_interval: 10

- platform: template
  switches:
    all_lights_off:
      value_template: "{{ True }}"
      turn_on:
      turn_off:
      - service: script.all_lights_off

- platform: flux
  lights:
  - light.man_cave_lights
  name: Man Cave Fluxer
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900

- platform: flux
  lights:
  - light.couch_lamp
  - light.living_room_ambience_1
  - light.living_room_ambience_2
  - light.love_seat_lamp
  name: Living Room Fluxer
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900

- platform: flux
  lights:
  - light.couch_lamp
  - light.living_room_ambience_1
  - light.living_room_ambience_2
  - light.love_seat_lamp
  name: Living Room Fluxer Fast
  transition: 1
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900