title: Mobile
custom_header:
  compact_mode: true
  footer_mode: true
views:
- !include /config/lovelace/views/mobile/favorites.yaml
- !include /config/lovelace/views/mobile/rooms.yaml
- !include /config/lovelace/views/mobile/climate.yaml
- !include /config/lovelace/views/mobile/security.yaml
- !include /config/lovelace/views/mobile/cameras.yaml
- !include /config/lovelace/views/mobile/chores.yaml
- !include /config/lovelace/views/mobile/meal-plan.yaml
- !include /config/lovelace/views/mobile/network.yaml

