title: Casa Molina
custom_header:
  compact_mode: true
  hide_tabs: devm,systemm
  footer_mode: true
  hide_unused: true
  hide_config: true
  exceptions:
  - conditions:
      user_agent: Mobile
    config:
      show_tabs: light-control,devm,scene,lights,systemm
  - conditions:
      user: 'ManCaveTablet'
    config:
      hide_tabs: '*'
      show_tabs: 'main-panel-mc,scene,system'
  - conditions:
      user: 'Kaitlyn'
    config:
      hide_tabs: '*'
      show_tabs: 'light-control'
views:
  - !include /config/lovelace/views/mobile-light-control.yaml
  - !include /config/lovelace/views/lighting-scenes/lighting-scenes.yaml
  - !include /config/lovelace/views/main-panel/tablet-view.yaml
  - !include /config/lovelace/views/main-panel/mobile-view.yaml 
  - !include /config/lovelace/views/user/man_cave_tablet/main-panel.yaml
  
  - title: Man Cave
    path: man-cave
    icon: mdi:guitar-electric
    cards:
    - type: vertical-stack
      cards:
      - type: entities
        title: Man Cave
        show_header_toggle: false
        entities:
        - entity: light.man_cave_lights
          name: Lights
        - type: divider
        - type: "custom:slider-entity-row"
          toggle: true
          entity: light.ge_softwhite_102
          name: Floor Lamp
          icon: mdi:floor-lamp
        - type: "custom:slider-entity-row"
          toggle: true
          entity: light.ge_softwhite_103
          name: Reading Lamp
          icon: mdi:lamp
        - type: divider
        - entity: light.flex_strip_101
          name: Ambience
          icon: mdi:led-strip
        - entity: switch.man_cave_fluxer
          name: Flux
          icon: mdi:brightness-4
        - type: divider
        - entity: sensor.man_cave_temperature
          name: Ecobee Sensor
        style: |
          .card-header {
            padding-bottom: 5px;
          }
    - type: vertical-stack
      cards:
      - !include /config/lovelace/tiles/simple-thermostat-card.yaml
      # - type: glance
      #   entities:
      #   - entity: binary_sensor.desktop_pc
      #   - entity: binary_sensor.mini_pc
      #   - entity: binary_sensor.work_laptop
      #   - entity: binary_sensor.diskstation
      #   - entity: binary_sensor.google
      #     name: Internet
        # show_state: false
      - !include /config/lovelace/tiles/todo-card.yaml

    
  - title: Living Room
    path: living-room
    icon: mdi:sofa
    panel: true
    cards:
    - type: horizontal-stack
      cards:
      - type: vertical-stack #############COLUMN 1
        cards:
        - type: entities
          show_header_toggle: false
          entities:
          - entity: light.hue_color_a19_102
            type: "custom:slider-entity-row"
            toggle: true
            name: End Table Left
            icon: mdi:lamp
          - entity: light.hue_color_a19_103
            type: "custom:slider-entity-row"
            toggle: true
            name: End Table Right
            icon: mdi:lamp
          - entity: light.flex_strip_105
            icon: mdi:television
            toggle: true
          - entity: light.ledge_strips
            name: Ledge Light
            icon: mdi:weather-sunset-up
          - entity: switch.bar_lights
            name: Bar Lights
            icon: mdi:light-switch
          - type: divider
          - entity: switch.living_room_fluxer
            icon: mdi:brightness-4
            name: Flux
          - type: divider
          - type: "custom:simple-thermostat"
            name: false
            entity: climate.thermostat
            step_size: 1
            modes:
              cool:
                include: false
              auxHeatOnly:
                include: false
              heat:
                include:
                  false
              auto:
                include:
                  false
              "off":
                include:
                  false
      - type: vertical-stack #############COLUMN 2
        cards:
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            entity: switch.ikea_outlet_2
            service: switch.toggle
            icon: mdi:air-filter
            name: Air Purifier
            styles:
              card:
              - height: 75px
          - type: "custom:button-card"
            entity: script.living_room_on
            service: script.living_room_on
            icon: mdi:power
            name: Turn Room On
            styles:
              card:
              - height: 75px
        # - type: horizontal-stack
          # cards:
        - type: "custom:mini-media-player"
          service: media_player.toggle
          icon: mdi:television
          entity: media_player.living_room_tv
        - type: "custom:mini-media-player"
          entity: media_player.living_room_receiver
          icon: mdi:set-top-box
        - type: "custom:mini-media-player"
          entity: media_player.portable_speaker
          icon: mdi:speaker-wireless

  - !include /config/lovelace/views/vacuum-control.yaml


  - title: Automation
    path: automation
    icon: mdi:arrow-decision-auto
    cards:
    - type: history-graph
      hours_to_show: 36
      title: Automation Mode
      entities:
      - input_select.automation_mode
    - !include /config/lovelace/tiles/automation-mode-card.yaml
  
  - !include /config/lovelace/views/lights.yaml

  - title: System Monitor
    path: system
    icon: mdi:chart-line
    panel: true
    cards:
    - type: custom:hui-horizontal-stack-card
      cards:
      - !include /config/lovelace/tiles/system-monitor-card.yaml
      - !include /config/lovelace/tiles/network-status.yaml
      - !include /config/lovelace/tiles/device-status-card.yaml

  - title: System Monitor
    path: systemm
    icon: mdi:chart-line
    panel: true
    cards:
    - type: custom:hui-vertical-stack-card
      cards:
      - !include /config/lovelace/tiles/system-monitor-card.yaml
      - !include /config/lovelace/tiles/network-status.yaml
      - !include /config/lovelace/tiles/device-status-card.yaml
  
  - title: Battery
    path: battery
    icon: mdi:battery
    panel: true
    cards:
    - type: custom:auto-entities
      card:
        type: custom:bar-card
        severity:
        - value: 50
          color: '#bf4040'
        - value: 75
          color: '#bf9540'
        - value: 100
          color: '#40bf40'
        title_position: inside
        columns: 3
        padding: 2px
        align: left
        title_style:
          font-size: 16px
        value_style:
          font-size: 8px
      filter:
        include:
        - entity_id: "*_battery_level"
  