title: Casa Molina
custom_header:
  compact_mode: true
  hide_tabs: devm
  footer_mode: true
  hide_unused: true
  # hide_refresh: true
  # hide_help: true
  hide_config: true
  exceptions:
  - conditions:
      user_agent: Mobile
    config:
      show_tabs: light-control,devm
  - conditions:
# Include external resources
resources:
  - url: /local/roborock.js
    type: js
  - url: /local/slider-entity-row.js
    type: module
  - url: /local/button-card.js?v=3.1.1
    type: module
  - url: /local/card-mod.js?v=1.0.1
    type: module
  - url: /local/simple-thermostat.js?v=1.0.0.0.13
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.5.0
    type: module
  - url: /local/custom.css
    type: css
  - url: /local/mini-media-player-bundle.js?v=1.5.2
    type: module
  - url: /local/markdown-mod.js?v=1.0.0.0
    type: module
  - url: /local/my-custom-card.js?v=0.0.0.12
    type: js
  - url: /local/content-card-example.js
    type: js
  - url: /local/simple-dark-sky-card.js?v=1.0.0
    type: js
  - url: /local/gators-mbk-tracker.js?v=1.0.2
    type: js
  - url: /local/custom-header.js?v=1.3.2
    type: module

views:
  - !include /config/lovelace/views/mobile-light-control.yaml
  - !include /config/lovelace/views/lighting-scenes/lighting-scenes.yaml
  - !include /config/lovelace/views/main-panel/tablet-view.yaml
  - !include /config/lovelace/views/main-panel/mobile-view.yaml 
  
  - title: Man Cave
    path: man-cave
    icon: mdi:guitar-electric
    cards:
    - type: vertical-stack
      cards:
      - type: entities
        title: Man Cave
        show_header_toggle: false
        entities:
        - type: entity
          entity: light.man_cave_lights
          name: Lights
        - type: divider
        - type: "custom:slider-entity-row"
          toggle: true
          entity: light.ge_softwhite_102
          name: Floor Lamp
          icon: mdi:floor-lamp
        - type: "custom:slider-entity-row"
          toggle: true
          entity: light.ge_softwhite_103
          name: Reading Lamp
          icon: mdi:lamp
        - type: divider
        - type: entity
          entity: light.flex_strip_101
          name: Ambience
          icon: mdi:led-strip
        - type: switch
          entity: switch.man_cave_fluxer
          name: Flux
          icon: mdi:brightness-4
        - type: divider
        - type: sensor
          entity: sensor.man_cave_temperature
          name: Ecobee Sensor
        style: |
          .card-header {
            padding-bottom: 5px;
          }
    - type: vertical-stack
      cards:
      - !include /config/lovelace/tiles/simple-thermostat-card.yaml
      # - type: glance
      #   entities:
      #   - entity: binary_sensor.desktop_pc
      #   - entity: binary_sensor.mini_pc
      #   - entity: binary_sensor.work_laptop
      #   - entity: binary_sensor.diskstation
      #   - entity: binary_sensor.google
      #     name: Internet
        # show_state: false
      - !include /config/lovelace/tiles/todo-card.yaml

    
  - title: Living Room
    path: living-room
    icon: mdi:sofa
    panel: true
    cards:
    - type: horizontal-stack
      cards:
      - type: vertical-stack #############COLUMN 1
        cards:
        - type: entities
          show_header_toggle: false
          entities:
          - entity: light.love_seat_lamp
            type: "custom:slider-entity-row"
            toggle: true
            name: End Table Left
            icon: mdi:lamp
          - entity: light.couch_lamp
            type: "custom:slider-entity-row"
            toggle: true
            name: End Table Right
            icon: mdi:lamp
          - entity: light.flex_strip_105
            icon: mdi:television
            toggle: true
          - entity: light.ledge_strips
            name: Ledge Light
            icon: mdi:weather-sunset-up
          - entity: switch.bar_lights
            name: Bar Lights
            icon: mdi:light-switch
          - type: divider
          - entity: switch.living_room_fluxer
            type: switch
            icon: mdi:brightness-4
            name: Flux
          - type: divider
          - type: "custom:simple-thermostat"
            name: false
            entity: climate.thermostat
            step_size: 1
            modes:
              cool:
                include: false
              auxHeatOnly:
                include: false
              heat:
                include:
                  false
              auto:
                include:
                  false
              "off":
                include:
                  false
      - type: vertical-stack #############COLUMN 2
        cards:
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            entity: switch.ikea_outlet_2
            service: switch.toggle
            icon: mdi:air-filter
            name: Air Purifier
            styles:
              card:
              - height: 75px
          - type: "custom:button-card"
            entity: script.living_room_on
            service: script.living_room_on
            icon: mdi:power
            name: Turn Room On
            styles:
              card:
              - height: 75px
        # - type: horizontal-stack
          # cards:
        - type: "custom:mini-media-player"
          service: media_player.toggle
          icon: mdi:television
          entity: media_player.living_room_tv
        - type: "custom:mini-media-player"
          entity: media_player.living_room_receiver
          icon: mdi:set-top-box
        - type: "custom:mini-media-player"
          entity: media_player.portable_speaker
          icon: mdi:speaker-wireless

  - !include /config/lovelace/views/vacuum-control.yaml


  - title: Automation
    path: automation
    icon: mdi:arrow-decision-auto
    cards:
    - type: history-graph
      hours_to_show: 36
      title: Automation Mode
      entities:
      - input_select.automation_mode
    - !include /config/lovelace/tiles/automation-mode-card.yaml