title: Casa Molina
# Include external resources
resources:
  - url: /local/kiosk.js
    type: js
  - url: /local/roborock.js
    type: js
  - url: /local/slider-entity-row.js
    type: module
  - url: /local/button-card.js?v=3.0.0
    type: module
  - url: /local/card-mod.js?v=1.0.1
    type: module
  - url: /local/simple-thermostat.js?v=1.0.0.0.13
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.5.0
    type: module
  - url: /local/custom.css
    type: css
  - url: /local/mini-media-player-bundle.js?v=1.2.2
    type: module
  - url: /local/markdown-mod.js?v=1.0.0.0
    type: module

views:
  - !include /config/lovelace/views/mobile-light-control.yaml

  - title: Dashboard
    icon: mdi:view-dashboard-variant
    path: dashboard
    panel: false
    cards:
    # - type: horizontal-stack
      # cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: entities
            entities:
            - entity: binary_sensor.openclose_12
              name: Garage
            - entity: binary_sensor.google
              name: Internet
            - entity: sensor.temperature_20
              name: Outside Temp
            - entity: person.andrew
            style: |
              ha-card>div {
                padding-top: 8px!important;
                padding-bottom: 8px!important;
              }
          - !include /config/lovelace/tiles/simpler-thermostat-card.yaml
        - !include /config/lovelace/tiles/automation-mode-card.yaml
        - !include /config/lovelace/tiles/todo-card.yaml
      - type: vertical-stack
        cards:

        - type: entity-filter
          entities:
          - entity: group.kitchen_lights
            type: switch
            icon: mdi:fridge
            name: Kitchen Lights
          - entity: light.living_room_lights
            type: light
            icon: mdi:sofa
            name: Living Room Lights
          - entity: switch.ikea_outlet_3
            type: switch
            icon: mdi:weather-sunset-up
            name: Ledge Light
          - entity: light.man_cave_lights
            type: light
            icon: mdi:guitar-electric
            name: Man Cave Lights
          - entity: light.guest_room_lights
            type: light
            icon: mdi:bed-empty
            name: Guest Room Lights
          - entity: switch.ikea_outlet_2
            type: switch
            icon: mdi:air-purifier
            name: Air Purifier
          - entity: light.master_bedroom_lights
            type: light
            icon: mdi:bed-empty
            name: Master Bedroom Lights
          state_filter:
          - "on"
          show_empty: false
          card:
            type: entities
            title: Power Manager
            show_header_toggle: false

  - title: Man Cave
    path: man-cave
    icon: mdi:guitar-electric
    cards:
    - type: vertical-stack
      cards:
      - type: entities
        title: Man Cave
        show_header_toggle: false
        entities:
        - type: entity
          entity: light.man_cave_lights
          name: Lights
        - type: divider
        - type: "custom:slider-entity-row"
          toggle: true
          entity: light.ge_softwhite_102
          name: Floor Lamp
          icon: mdi:floor-lamp
        - type: "custom:slider-entity-row"
          toggle: true
          entity: light.ge_softwhite_103
          name: Reading Lamp
          icon: mdi:lamp
        - type: divider
        - type: entity
          entity: light.hue_color_a19_101
          name: Ambience
        - type: switch
          entity: switch.man_cave_fluxer
          name: Flux
          icon: mdi:brightness-4
        - type: divider
        - type: sensor
          entity: sensor.man_cave_temperature
          name: Ecobee Sensor
        style: |
          .card-header {
            padding-bottom: 5px;
          }
    - type: vertical-stack
      cards:
      - !include /config/lovelace/tiles/simple-thermostat-card.yaml
      # - type: glance
      #   entities:
      #   - entity: binary_sensor.desktop_pc
      #   - entity: binary_sensor.mini_pc
      #   - entity: binary_sensor.work_laptop
      #   - entity: binary_sensor.diskstation
      #   - entity: binary_sensor.google
      #     name: Internet
        # show_state: false
      - !include /config/lovelace/tiles/todo-card.yaml

    
  - title: Living Room
    path: living-room
    icon: mdi:sofa
    panel: true
    cards:
    - type: horizontal-stack
      cards:
      - type: vertical-stack #############COLUMN 1
        cards:
        - type: entities
          show_header_toggle: false
          entities:
          - entity: light.living_room_lights
            type: "custom:slider-entity-row"
            toggle: true
            name: Living Room Lights
          - type: divider
          - entity: light.love_seat_lamp
            type: "custom:slider-entity-row"
            toggle: true
            name: End Table Left
            icon: mdi:lamp
          - entity: light.couch_lamp
            type: "custom:slider-entity-row"
            toggle: true
            name: End Table Right
            icon: mdi:lamp
          - entity: switch.ikea_outlet_3
            name: Ledge Light
            icon: mdi:weather-sunset-up
          - entity: switch.bar_lights
            name: Bar Lights
            icon: mdi:light-switch
          - type: divider
          - entity: switch.living_room_fluxer
            type: switch
            icon: mdi:brightness-4
            name: Flux
          - type: divider
          - type: "custom:simple-thermostat"
            name: false
            entity: climate.thermostat
            step_size: 1
            modes:
              cool:
                include: false
              auxHeatOnly:
                include: false
              heat:
                include:
                  false
              auto:
                include:
                  false
              "off":
                include:
                  false
      - type: vertical-stack #############COLUMN 2
        cards:
        - type: horizontal-stack
          cards:
          - type: "custom:button-card"
            entity: switch.ikea_outlet_2
            service: switch.toggle
            icon: mdi:air-filter
            name: Air Purifier
            styles:
              card:
              - height: 75px
          - type: "custom:button-card"
            entity: script.living_room_on
            service: script.living_room_on
            icon: mdi:power
            name: Turn Room On
            styles:
              card:
              - height: 75px
        # - type: horizontal-stack
          # cards:
        - type: "custom:mini-media-player"
          service: media_player.toggle
          icon: mdi:television
          entity: media_player.living_room_tv
        - type: "custom:mini-media-player"
          entity: media_player.living_room_receiver
          icon: mdi:set-top-box
        - type: "custom:mini-media-player"
          entity: media_player.portable_speaker
          icon: mdi:speaker-wireless

  - !include /config/lovelace/views/vacuum-control.yaml


  - title: Automation
    path: automation
    icon: mdi:arrow-decision-auto
    cards:
    - type: history-graph
      hours_to_show: 36
      title: Automation Mode
      entities:
      - input_select.automation_mode
    - !include /config/lovelace/tiles/automation-mode-card.yaml
  
  - title: Dev
    path: dev
    cards:
    - type: picture-entity
      entity: camera.front_door
      camera_image: camera.front_door
    - type: entities
      entities:
      - binary_sensor.skybell_front_door_button
      - binary_sensor.skybell_front_door_motion
      - cover.garage_door
    
    
      
    # - type: "custom:button-card"
    #   entity: switch.ikea_outlet_2
    #   service: switch.toggle
    #   icon: mdi:air-filter
    #   name: Air Purifier
    #   styles:
    #     card:
    #       - height: 75px