title: Home Assistant
custom_header:
  compact_mode: true
views:
- !include /config/lovelace/views/wall-tablet/home.yaml
- !include /config/lovelace/views/shared/cameras.yaml
- !include /config/lovelace/views/shared/doorbell-cameras.yaml
- !include /config/lovelace/views/shared/rooms.yaml
- !include /config/lovelace/views/shared/climate.yaml
- !include /config/lovelace/views/shared/chores.yaml
- !include /config/lovelace/views/shared/meal-plan.yaml
- !include /config/lovelace/views/shared/system-monitor.yaml
- !include /config/lovelace/views/shared/network.yaml
