card: 'custom:button-card'
conditionalClass: |
  [[[
    return "sub-menu";
  ]]]
tap_action:
  action: navigate
  haptic: selection
  navigation_path: /sub-automations/0
hold_action:
  action: navigate
  haptic: selection
  navigation_path: /sub-automations/0
cardOptions:
  name: Automation
  icon: 'mdi:home-automation'
  size: 80%
  show_name: true
  show_state: false
  show_label: false
  styles:
    card:
      - '-webkit-box-shadow': none
      - box-shadow: none
      - background-color: 'rgba(255, 255, 255, 0.0)'
    name:
      - color: 'rgb(255, 255, 255, 0.7)'
    icon:
      - font-family: Arial
      - color: 'rgb(255, 255, 255, 0.7)'