


    


- alias: Nobody Home Notification Action Clicked - Home Mode
  trigger:
  - event_data:
      action: automation_mode_home
    event_type: html5_notification.clicked
    platform: event
  condition:
    condition: template
    value_template: '{{ states("input_select.automation_mode") not in ["guest", "vacation", "home"] }}'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.automation_mode
      option: home


  
