- alias: Laundry Room Motion
  trigger:
  - entity_id: binary_sensor.presence_5
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '04:00:00'
    before: '22:00:00'
    condition: time
  action:
  - data:
      brightness: '255'
      entity_id: ' light.laundry_room_lights'
      transition: 2
    service: light.turn_on
- alias: Laundry Room Motion (Late Night)
  trigger:
  - entity_id: binary_sensor.presence_5
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '22:00:00'
    before: '04:00:00'
    condition: time
  action:
  - data:
      brightness: '63'
      entity_id: ' light.laundry_room_light_1'
      transition: 2
    service: light.turn_on

- alias: Laundry Room No-Motion
  trigger:
  - entity_id: binary_sensor.presence_5
    for:
      minutes: 5
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      brightness: '0'
      entity_id: ' light.laundry_room_lights'
      transition: '5'
    service: light.turn_on

- alias: Startup Init Theme
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: slate
    service: frontend.set_theme

- alias: Bedroom Motion - Home Mode
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '04:00:00'
    before: '08:00:00'
  - condition: state
    entity_id: input_select.automation_mode
    state: sleep
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.automation_mode
      option: home

- alias: Phone Orientation Down - Sleep Mode
  trigger:
  - platform: state
    entity_id: input_boolean.tasker_phone_orientation
    to: 'on'
    for: 00:05:00
  condition:
  - condition: state
    entity_id: person.andrew
    state: home
  - condition: template
    value_template: '{{ states("input_select.automation_mode") in ["home"] }}'
  - condition: time
    after: '21:00:00'
    before: '02:00:00'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.automation_mode
      option: sleep
  
  
    

  # alias: Lights Auto-off
  # trigger:
  #   platform: time
  #   at: 00:00:00
  # action:
  # - service: switch.turn_off
  #   data:
  #     entity_id: switch.power_outlet_1
  # - service: switch.turn_off
  #   data:
  #     entity_id: switch.power_outlet_2
  # - service: switch.turn_off
  #   data:
  #     entity_id: switch.ikea_outlet_1
  # - service: light.turn_off
  #   data:
  #     entity_id: light.living_room_lights
  # - service: light.turn_off
  #   data:
  #     entity_id: light.man_cave_lights






# - alias: Good Morning
#   trigger:
#   - platform: time
#     at: 06:00:00
#   condition:
#   - condition: state
#     entity_id: group.all_device_trackers
#     state: home
#   action:
#   - service: script.good_morning

- alias: Kaitlyn's iPhone Home - Set Thermostat Cool Temp
  trigger:
  - platform: state
    entity_id: device_tracker.iphone
    from: not_home
    to: home
  condition:
  - condition: template
    value_template: '{{ states("climate.thermostat") == "cool" and state_attr("climate.thermostat", "temperature") > 76 }}'
  action:
  - service: climate.set_temperature
    data:
      entity_id: climate.thermostat
      temperature: 76
    
- alias: Nobody Home - Away Mode
  trigger:
  - entity_id: sensor.anybody_home
    platform: state
    from: 'True'
    to: 'False'
  condition:
    condition: template
    value_template: '{{ states("input_select.automation_mode") not in ["guest", "vacation", "away"] }}'
  action:
  - data:
      message: Home assistant detected that nobody is home.
      title: Activing Away Mode
      data:
        url: dev
        actions:
        - action: automation_mode_home
          title: Cancel
        tag: nobody-is-home
    service: notify.html5_notifications
  - service: input_select.select_option
    data:
      entity_id: input_select.automation_mode
      option: away

- alias: Nobody Home Notification Action Clicked - Home Mode
  trigger:
  - event_data:
      action: automation_mode_home
    event_type: html5_notification.clicked
    platform: event
  condition:
    condition: template
    value_template: '{{ states("input_select.automation_mode") not in ["guest", "vacation", "home"] }}'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.automation_mode
      option: home

- alias: Anybody Home - Home Mode
  trigger:
  - entity_id: sensor.anybody_home
    platform: state
    from: 'False'
    to: 'True'
  condition:
    condition: template
    value_template: '{{ states("input_select.automation_mode") not in ["guest", "vacation", "home"] }}'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.automation_mode
      option: home