- alias: Chores.Reminders.WetFoodNight
  trigger:
  - entity_id: calendar.cat_chores_wet_food_night
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: input_boolean.chewie_wet_food
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.chewie_water
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.chewie_litter
    service: input_boolean.turn_on

- alias: Reminders.Recycling.EventTrigger
  trigger:
  - entity_id: sensor.recycling_collection_offset_reached
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: input_boolean.take_recycling_out
    service: input_boolean.turn_on

- alias: Reminders.Garbage.EventTrigger
  trigger:
  - entity_id: sensor.garbage_collection_offset_reached
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: input_boolean.take_garbage_out
    service: input_boolean.turn_on

- alias: Reminders.Garbage.EventEnd
  trigger:
  - entity_id: sensor.garbage_collection_offset_reached
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: input_boolean.take_garbage_out
    service: input_boolean.turn_off

- alias: Reminders.Recycling.EventEnd
  trigger:
  - entity_id: sensor.recycling_collection_offset_reached
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: input_boolean.take_recycling_out
    service: input_boolean.turn_off