- alias: Guest Room Dimmer Switch On (keydown)
  trigger:
  - event_data:
      event: 1000
      id: guest_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.guest_room_lights
    service: light.turn_on
    
- alias: Guest Room Dimmer Switch On (hold)
  trigger:
  - event_data:
      event: 1001
      id: guest_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.guest_room_lights
      brightness: '255'
    service: light.turn_on

- alias: Guest Room Dimmer Switch Off (keydown)
  trigger:
  - event_data:
      event: 4000
      id: guest_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.guest_room_lamp_2
    service: light.turn_off

- alias: Guest Room Dimmer Switch Off (hold)
  trigger:
  - event_data:
      event: 4001
      id: guest_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.guest_room_lights
    service: light.turn_off

- alias: Guest Room Dimmer Switch BrightUp (press)
  trigger:
  - event_data:
      event: 2000
      id: guest_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
    service: script.lights_bright_up
    data:
      entity_id: light.guest_room_lights

- alias: Guest Room Dimmer Switch BrightUp (hold)
  trigger:
  - event_data:
      event: 2001
      id: guest_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
    service: light.turn_on
    data:
      entity_id: light.guest_room_lights
      brightness: '255'

- alias: Guest Room Dimmer Switch BrightDown (press)
  trigger:
  - event_data:
      event: 3000
      id: guest_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
    service: script.lights_bright_down
    data:
      entity_id: light.guest_room_lights

- alias: Guest Room Dimmer Switch BrightDown (hold)
  trigger:
  - event_data:
      event: 3001
      id: guest_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
    service: light.turn_on
    data:
      entity_id: light.guest_room_lights
      brightness: 1