
- alias: Living Room Dimmer Switch On (keydown)
  trigger:
  - event_data:
      event: 1000
      id: living_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.living_room_lights
    service: light.turn_on

- alias: Living Room Dimmer Switch On (hold)
  trigger:
  - event_data:
      event: 1001
      id: living_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.ikea_outlet_1
    service: switch.turn_on

- alias: Living Room Dimmer Switch Off (keydown)
  trigger:
  - event_data:
      event: 4000
      id: living_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.living_room_lights
    service: light.turn_off

- alias: Living Room Dimmer Switch Off (hold)
  trigger:
  - event_data:
      event: 4001
      id: living_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.ikea_outlet_1
    service: switch.turn_off

- alias: Living Room Dimmer Switch BrightUp (press)
  trigger:
  - event_data:
      event: 2000
      id: living_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.living_room_lights
    service: script.lights_bright_up
  - data:
      entity_id: switch.living_room_fluxer
    service: switch.turn_off

- alias: Living Room Dimmer Switch BrightUp (hold)
  trigger:
  - event_data:
      event: 2001
      id: living_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.living_room_lights
      brightness: '255'
    service: light.turn_on
  - data:
      entity_id: switch.living_room_fluxer
    service: switch.turn_off

- alias: Living Room Dimmer Switch BrightDown (press)
  trigger:
  - event_data:
      event: 3000
      id: living_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.living_room_lights
    service: script.lights_bright_down
  - data:
      entity_id: switch.living_room_fluxer
    service: switch.turn_off

- alias: Living Room Dimmer Switch BrightDown (hold)
  trigger:
  - event_data:
      event: 3001
      id: living_room_dimmer_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.living_room_lights
      brightness: '3'
    service: light.turn_on
  - data:
      entity_id: switch.living_room_fluxer
    service: switch.turn_off