- alias: Andrew Enters Shopping Zone - Push Notification
  trigger:
  - entity_id: person.andrew
    platform: state
    to: !secret grocery_store_1_name
  - entity_id: person.andrew
    platform: state
    to: !secret wholesale_store_1_name
  condition: []
  action:
  - data_template:
      message: Andrew is at {{ states("person.andrew") }}. Do you need anything?
    service: notify.html5_notifications
  - data_template:
      message: Andrew is at {{ states("person.andrew") }}. Do you need anything?
    service: notify.mobile_app_kaitlyn_s_iphone