- alias: Andrew Enters Shopping Zone - Push Notification
  trigger:
  - entity_id: person.andrew
    platform: state
    to: Publix (9th Ave)
  - entity_id: person.andrew
    platform: state
    to: Sam's Club
  condition: []
  action:
  - data_template:
      message: Andrew is at {{ states("person.andrew") }}. Do you need anything?
    service: notify.html5_notifications

- alias: Close Garage Door Reminder Notification
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.openclose_12
    state: 'on'
  action:
  - data:
      message: Garage Door left open!
    service: notify.html5_notifications

# - alias: Front Door Motion Notification
#   trigger:
#   - entity_id: binary_sensor.presence_19
#     from: 'off'
#     platform: state
#     to: 'on'
#   condition: []
#   action:
#   - data:
#       message: Motion detected at Front Door
#       data:
#         tag: front-door-motion
#     service: notify.html5_notifications