- alias: Tap Switch 1 - I (off)
  trigger:
  - event_data:
      event: 34
      id: tap_switch_1
    event_type: deconz_event
    platform: event
  condition:
  - condition: state
    entity_id: light.man_cave_lights
    state: 'on'
  action:
  - data:
      entity_id: light.man_cave_lights
    service: light.turn_off
    
- alias: Tap Switch 1 - I (on)
  trigger:
  - event_data:
      event: 34
      id: tap_switch_1
    event_type: deconz_event
    platform: event
  condition:
  - condition: state
    entity_id: light.man_cave_lights
    state: 'off'
  action:
  - data:
      entity_id: light.man_cave_lights
    service: light.turn_on

- alias: Tap Switch 1 - II
  trigger:
  - event_data:
      event: 16
      id: tap_switch_1
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      brightness: '74'
      color_temp: '500'
      entity_id: light.man_cave
    service: light.turn_on
  - data:
      brightness: '1'
      entity_id: light.man_cave_dimmable
    service: light.turn_on

- alias: Tap Switch 1 - III
  trigger:
  - event_data:
      event: 17
      id: tap_switch_1
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      brightness: '170'
      color_temp: '327'
      entity_id: light.man_cave
    service: light.turn_on
  - data:
      brightness: '100'
      entity_id: light.man_cave_dimmable
    service: light.turn_on

- alias: Tap Switch 1 - IIII
  trigger:
  - event_data:
      event: 18
      id: tap_switch_1
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      brightness: '255'
      color_temp: '225'
      entity_id: light.man_cave_lights
    service: light.turn_on