- alias: iSuck Large Clean Complete
  trigger:
    platform: state
    entity_id: vacuum.isuck
    from: cleaning
    to: returning
  condition:
  - condition: template
    value_template: '{{ state_attr(''vacuum.isuck'', ''cleaned_area'') > 70 }}'
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.isuck_last_clean_time
    data_template:
      time: '{{ (as_timestamp(state_attr("vacuum.isuck", "clean_start")) | timestamp_custom("%H:%M:%S",
        true)) }}'
      date: '{{ (as_timestamp(state_attr("vacuum.isuck", "clean_start")) | timestamp_custom("%Y-%m-%d",
        true)) }}'
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.isuck_brush_dirty

- alias: iSuck Medium Clean Complete
  trigger:
    platform: state
    entity_id: vacuum.isuck
    from: cleaning
    to: returning
  condition:
  - condition: template
    value_template: '{{ state_attr(''vacuum.isuck'', ''cleaned_area'') > 10 }}'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.isuck_dust_bin_full