skybell:
  username: !secret skybell_username
  password: !secret skybell_password

binary_sensor:
- platform: skybell
  monitored_conditions:
  - button
  - motion

camera:
- platform: skybell
  monitored_conditions:
  # - avatar
  - activity