skybell:
  username: !secret skybell_username
  password: !secret skybell_password

binary_sensor:
- platform: skybell
  monitored_conditions:
  - button
  - motion

camera:
- platform: skybell
  monitored_conditions:
  - avatar
  - activity
  activity_name: "Last Activity"

# Example configuration.yaml entry
switch:
- platform: skybell
  monitored_conditions:
  - do_not_disturb
  - motion_sensor