###################################################################
#
# Door Sensors
# ------
#
#   This package contains configuration for door sensor automation.
#
# Features
# --------
# 
#  * Define light groups (creates single light entities)
#  * Sync kitchen cabinet lights
#
###################################################################

homeassistant:
  customize:
    binary_sensor.openclose_12:
      templates:
        icon_color: >
          if (state == "off") return 'var(--primary-text-color)';
          else if (states("sun.sun") == "above_horizon") return 'var(--secondary-text-color)';
          else return 'var(--status-color-alert)';
        icon: >
          if (state == "on") return "mdi:garage-open";
          else return "mdi:garage";

automation:
- alias: Garage Open [After 10:00PM] - Brighten Driveway Lights
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_12
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.driveway_lights
    state: 'on'
  - condition: time
    after: '22:00:00'
    before: 08:00:00
  action:
  - data:
      brightness: '255'
      entity_id: light.driveway_lights
    service: light.turn_on

- alias: Garage Close [After 10:00PM] - Dim Driveway Lights
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_12
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: light.driveway_lights
    state: 'on'
  - condition: time
    after: '22:00:00'
    before: 08:00:00
  action:
  - data:
      brightness: '1'
      entity_id: light.driveway_lights
    service: light.turn_on

# - alias: Man Cave Door Open [workday morning] - Turn On Man Cave Lights
#   trigger:
#   - platform: state
#     entity_id: binary_sensor.openclose_15
#     from: 'off'
#     to: 'on'
#   condition:
#   - condition: time
#     after: 04:00:00
#     before: '10:00:00'
#     weekday:
#     - mon
#     - tue
#     - wed
#     - thu
#     - fri
#   action:
#   - service: light.turn_on
#     data:
#       entity_id: light.man_cave_lights
#   - service: switch.turn_on
#     data:
#       entity_id: switch.man_cave_fluxer

- alias: Garage Door Open Alerts
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_12
    from: 'off'
    to: 'on'
  action:
  - service: rest_command.tasker_garage_opened
  - service: script.man_cave_alert