switch:
# - platform: flux
#   lights:
#   - light.man_cave_lights
#   name: Man Cave Fluxer
#   start_colortemp: 6500
#   sunset_colortemp: 3400
#   stop_colortemp: 1900

- platform: flux
  lights:
  - light.man_cave_lights
  name: Man Cave Fluxer Fast
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900
  transition: 1

- platform: flux
  lights:
  - light.couch_lamp
  - light.living_room_ambience_1
  - light.living_room_ambience_2
  - light.love_seat_lamp
  name: Living Room Fluxer
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900

- platform: flux
  lights:
  - light.couch_lamp
  - light.living_room_ambience_1
  - light.living_room_ambience_2
  - light.love_seat_lamp
  name: Living Room Fluxer Fast
  transition: 1
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900