switch:
- platform: flux
  lights:
  - light.hue_color_a19_101
  name: Man Cave Fluxer
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900

- platform: flux
  lights:
  - light.couch_lamp
  - light.love_seat_lamp
  name: Living Room Fluxer
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900

- platform: flux
  lights:
  - light.couch_lamp
  - light.love_seat_lamp
  name: Living Room Fluxer Fast
  transition: 1
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900