switch:
- platform: flux
  lights:
  - light.flex_strip_101
  name: Man Cave Fluxer
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900
  disable_brightness_adjust: true
  mode: rgb

- platform: flux
  lights:
  - light.couch_lamp
  - light.love_seat_lamp
  name: Living Room Fluxer
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900

- platform: flux
  lights:
  - light.couch_lamp
  - light.love_seat_lamp
  name: Living Room Fluxer Fast
  transition: 1
  start_colortemp: 6500
  sunset_colortemp: 3400
  stop_colortemp: 1900