input_boolean:
  ledge_fluxer:
      name: 'Ledge Fluxer'
  great_room_shuffler:
      name: 'Great Room Shuffler'
  man_cave_fluxer:
      name: 'Man Cave Fluxer'
  man_cave_shuffler:
      name: 'Man-cave Shuffler'

sensor:
- platform: template
  sensors:
    daylight_kelvin:
      value_template: '{{ states("input_number.daylight_kelvin") }}'

input_number:
  daylight_kelvin:
    name: Daylight Kelvin
    min: 0
    max: 10000
  circadian_brightness:
    name: Circadian Brightness
    min: 0
    max: 255

input_text:
  daylight_rgb:
    name: Daylight RGB

switch:

- platform: template
  switches:
    ledge_fluxer:
      value_template: "{{ is_state('input_boolean.ledge_fluxer', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ledge_fluxer
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.ledge_fluxer

    man_cave_fluxer:
      value_template: "{{ is_state('input_boolean.man_cave_fluxer', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.man_cave_fluxer
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.man_cave_fluxer

    great_room_shuffler:
      value_template: "{{ is_state('input_boolean.great_room_shuffler', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.great_room_shuffler
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.great_room_shuffler

    man_cave_shuffler:
      value_template: "{{ is_state('input_boolean.man_cave_shuffler', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.man_cave_shuffler
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.man_cave_shuffler

homeassistant:
  customize:
    sensor.daylight_kelvin:
      unit_of_measurement: 'Kelvin'