###################################################################
#
# Lights
# ------
#
#   This package contains configuration for lighting automation.
#
# Features
# --------
# 
#  * Define light groups (creates single light entities)
#  * Sync kitchen cabinet lights
#  * 
#
###################################################################


light:
- platform: group
  name: Guest Room Lights
  entities:
    - light.guest_room_lamp_1
    - light.guest_room_lamp_2
    - light.flex_strip_103
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.kp_bedside
    - light.andrew_bedside
- platform: group
  name: Man-cave Lights
  entities:
    - light.flex_strip_101
    - light.flex_strip_102
    - light.hue_color_a19_101
    - light.flex_strip_106
    - light.flex_strip_111
- platform: group
  name: Interior Lights
  entities:
  - light.hue_color_a19_103
  - light.hue_color_a19_102
  - light.great_room_strips
  - light.guest_room_lights
  - light.master_bedroom_lights
  - light.man_cave_lights
  - light.hue_softwhite_lwb014_101
  - light.garage_lights
- platform: group
  name: Exterior Lights
  entities:
  - light.ge_softwhite_101
  - light.ge_softwhite_104
- platform: group
  name: Man Cave Flex Strips
  entities:
  - light.flex_strip_101
  - light.flex_strip_102
  - light.flex_strip_106
- platform: group
  name: Back Yard Lights
  entities:    
  - light.back_yard_strand_lights
  - light.back_yard_spot_light
  - light.back_yard_strand_lights_2
  - light.back_yard_swing_lights
- platform: group
  name: Ledge Strips
  entities:
  - light.flex_strip_104
  - light.flex_strip_108
  - light.flex_strip_107
  - light.flex_strip_109
  - light.flex_strip_110
- platform: group
  name: Great Room Strips
  entities:
  - light.flex_strip_104
  - light.flex_strip_108
  - light.flex_strip_107
  - light.flex_strip_109
  - light.flex_strip_110
  - light.flex_strip_105
- platform: group
  name: Kitchen Lights
  entities:
  - light.kitchen_bar_lights
  - light.kitchen_cabinet_lights
  - light.kitchen_overhead_lights
  - light.kitchen_table_lights

- platform: group
  name: Garage Lights
  entities:
  - light.flex_strip_112
  - light.pegboard_lights

- platform: switch
  name: Pegboard Lights
  entity_id: switch.ikea_outlet_101

- platform: template
  lights:
    wall_tablet_backlight:
      friendly_name: Wall Tablet Backlight
      value_template: '{{ states.sensor.wall_tablet_kiosk_device_info.attributes["screenOn"] }}'
      level_template: '{{ states.sensor.wall_tablet_kiosk_device_info.attributes["screenBrightness"] }}'
      turn_on:
        service: rest_command.wall_tablet_kiosk_command
        data:
          cmd: screenOn
      turn_off:
        service: rest_command.wall_tablet_kiosk_command
        data:
          cmd: screenOff
      set_level:
      - service: rest_command.wall_tablet_kiosk_command
        data:
          cmd: screenOn
      - service: rest_command.wall_tablet_kiosk_command
        data_template:
          cmd: setStringSetting
          key: screenBrightness
          value: '{{ brightness }}'
      
    samsung_tablet_1001_backlight:
      friendly_name: Wall Tablet Backlight
      value_template: '{{ states.sensor.samsung_tablet_1001_kiosk_device_info.attributes["screenOn"] }}'
      level_template: '{{ states.sensor.samsung_tablet_1001_kiosk_device_info.attributes["screenBrightness"] }}'
      turn_on:
        service: rest_command.samsung_tablet_1001_kiosk_command
        data:
          cmd: screenOn
      turn_off:
        service: rest_command.samsung_tablet_1001_kiosk_command
        data:
          cmd: screenOff
      set_level:
        service: rest_command.samsung_tablet_1001_kiosk_command
        data_template:
          cmd: setStringSetting
          key: screenBrightness
          value: '{{ brightness }}'
    
    man_cave_tablet_backlight:
      friendly_name: Man-cave Backlight
      value_template: '{{ states.sensor.man_cave_tablet_kiosk_device_info.attributes["screenOn"] }}'
      level_template: '{{ states.sensor.man_cave_tablet_kiosk_device_info.attributes["screenBrightness"] }}'
      turn_on:
        service: rest_command.man_cave_tablet_kiosk_command
        data:
          cmd: screenOn
      turn_off:
        service: rest_command.man_cave_tablet_kiosk_command
        data:
          cmd: screenOff
      set_level:
      - service: rest_command.man_cave_tablet_kiosk_command
        data:
          cmd: screenOn
      - service: rest_command.man_cave_tablet_kiosk_command
        data_template:
          cmd: setStringSetting
          key: screenBrightness
          value: '{{ brightness }}'

    lenovo_tablet_701_backlight:
      friendly_name: Garage Tablet Backlight
      value_template: '{{ states.sensor.lenovo_tablet_701_kiosk_device_info.attributes["screenOn"] }}'
      level_template: '{{ states.sensor.lenovo_tablet_701_kiosk_device_info.attributes["screenBrightness"] }}'
      turn_on:
        service: rest_command.lenovo_tablet_701_kiosk_command
        data:
          cmd: screenOn
      turn_off:
        service: rest_command.lenovo_tablet_701_kiosk_command
        data:
          cmd: screenOff
      set_level:
        service: rest_command.lenovo_tablet_701_kiosk_command
        data_template:
          cmd: setStringSetting
          key: screenBrightness
          value: '{{ brightness }}'

script:
  lights_bright_up:
    alias: Lights Brightness Up
    sequence:
    - service: light.turn_on
      data_template:
        entity_id: "{{ entity_id }}"
        brightness: >
          {% set n = (state_attr(entity_id, "brightness") | int) + 50 %}
          {% if n > 254 %}
          254
          {% else %}
          {{ n }}
          {% endif %}

  lights_bright_down:
    alias: Lights Brightness Down
    sequence:
    - service: light.turn_on
      data_template:
        entity_id: "{{ entity_id }}"
        brightness: >
          {% set n = state_attr(entity_id, 'brightness') | int - 50 %}
          {% if n < 4 %}
          4
          {% else %}
          {{ n }}
          {% endif %}

  all_lights_off:
    alias: All Lights Off
    sequence:
    - service: light.turn_off
      data:
        entity_id: group.all_lights
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_light_switches

  turn_off_interior_lights:
    alias: Turn Off Interior Lights
    sequence:
    - service: light.turn_off
      data:
        entity_id: light.interior_lights
    - service: homeassistant.turn_off
      data:
        entity_id:
        - group.interior_light_switches

  turn_on_interior_lights:
    alias: Turn On Interior Lights
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.interior_lights
    - service: homeassistant.turn_on
      data:
        entity_id: group.interior_light_switches
  
  turn_on_kitchen_lights:
    alias: Turn On Kitchen Lights
    sequence:
    - service: homeassistant.turn_on
      entity_id:
      - group.kitchen_lights

  turn_off_kitchen_lights:
    alias: Turn On Kitchen Lights
    sequence:
    - service: homeassistant.turn_off
      entity_id:
      - group.kitchen_lights
  
  man_cave_alert:
    alias: Man Cave Alert
    sequence:
    - service: light.toggle
      data:
        entity_id: light.ge_softwhite_102
    - delay:
        seconds: 1
    - service: light.toggle
      data:
        entity_id: light.ge_softwhite_102
    - delay:
        seconds: 1
    - service: light.toggle
      data:
        entity_id: light.ge_softwhite_102
    - delay:
        seconds: 1
    - service: light.toggle
      data:
        entity_id: light.ge_softwhite_102
    - delay:
        seconds: 1
    - service: light.toggle
      data:
        entity_id: light.ge_softwhite_102
    - delay:
        seconds: 1
    - service: light.toggle
      data:
        entity_id: light.ge_softwhite_102
  
  # Used when the motion sensor is triggered
  man_cave_auto_lights:
    alias: Man Cave Auto Lights
    sequence:
    - service: light.turn_on
      entity_id: light.flex_strip_101
    - service: switch.turn_on
      entity_id: switch.man_cave_fluxer
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    - service: switch.turn_on
      entity_id: switch.ikea_smart_plug_101
  
  turn_on_exterior_lights:
    alias: Lighting Scene - Exterior Lights On
    sequence:
    - service: light.turn_on
      data:
        entity_id:
        - light.ge_softwhite_101
        brightness: '255'
    - service: light.turn_on
      entity_id: light.back_yard_lights

  turn_off_exterior_lights:
    alias: Lighting Scene - Exterior Lights Off
    sequence:
    - service: light.turn_off
      data:
        entity_id:
        - light.ge_softwhite_101
        - light.ge_softwhite_104
    - service: switch.turn_off
      entity_id: group.back_yard_lights

##################################
## Lighting Scenes
##
## Useful for Alexa commands
##
##################################

  lighting_scene_common_area_full_brightness:
    alias: Lighting Scene - Common Area Full Brightness
    sequence:
    - service: group.turn_on
      data:
        entity_id: light.living_room_lamps_deconz
        brightness: '255'
    - service: light.turn_on
      data:
        entity_id: light.kitchen_table_lights
        brightness: '127'
    - service: switch.turn_on
      entity_id:
      - switch.cabinet_lights
      - switch.bar_lights
      - switch.kitchen_overhead_lights
      - light.flex_strip_105
      - switch.xiaomi_wifi_smart_plug_101
      
  lighting_scene_common_area_off:
    alias: Lighting Scene - Common Area Off
    sequence:
    - service: homeassistant.turn_off
      entity_id:
      - group.kitchen_lights
      - light.living_room_lamps_deconz
    - service: switch.turn_off
      entity_id:
      - light.flex_strip_105
      - switch.xiaomi_wifi_smart_plug_101

  lighting_scene_common_area_dim:
    alias: Lighting Scene - Common Area Dim
    sequence:
    - service: group.turn_on
      data:
        entity_id: light.living_room_lamps_deconz
        brightness: '100'
    - service: switch.turn_on
      entity_id: 
      - light.flex_strip_105
      - switch.xiaomi_wifi_smart_plug_101
    - service: homeassistant.turn_off
      entity_id:
      - group.kitchen_lights
  
  lighting_scene_kitchen_lights_on:
    alias: Lighting Scene - Kitchen Lights On
    sequence:
    - service: switch.turn_on
      entity_id:
      - switch.cabinet_lights
      - switch.bar_lights
    - service: light.turn_on
      data:
        entity_id: light.kitchen_table_lights
        brightness: '63'

  lighting_scene_kitchen_lights_dim:
    alias: Lighting Scene - Kitchen Lights Dim
    sequence:
    - service: switch.turn_on
      entity_id: switch.kitchen_cabinet_lights
    - service: switch.turn_off
      entity_id:
      - switch.bar_lights
      - switch.kitchen_overhead_lights
    - service: light.turn_on
      data:
        entity_id: light.kitchen_table_lights
        brightness: '4'

  lighting_scene_kitchen_lights_off:
    alias: Lighting Scene - Kitchen Lights Off
    sequence:
    - service: homeassistant.turn_off
      entity_id: group.kitchen_lights
  
  lighting_scene_sleep_mode:
    alias: Lighting Scene - Home Sleep Mode
    sequence:
    - service: script.turn_off_interior_lights
    - service: homeassistant.turn_off
      entity_id: group.back_yard_lights
    - service: light.turn_on
      data:
        entity_id: light.ge_softwhite_104
        brightness: 50
