automation:
- alias: Turn off Air Purifier when TV turns on
  trigger:
  - entity_id: media_player.living_room_receiver
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: media_player.living_room_tv
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.ikea_outlet_2
    service: switch.turn_off

- alias: Turn on ambient lights when TV turns on
  trigger:
  - entity_id: media_player.living_room_receiver
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: media_player.living_room_tv
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.flex_strip_105
      brightness: 255
      transition: 5
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"

- alias: Turn off ambient lights when TV turns off
  trigger:
  - entity_id: media_player.living_room_receiver
    to: 'off'
    platform: state
    from: 'on'
  - entity_id: media_player.living_room_tv
    to: 'off'
    platform: state
    from: 'on'
  action:
  - service: light.turn_off
    entity_id: light.flex_strip_105