automation:
- alias: Turn off Air Purifier when TV turns on
  trigger:
  - entity_id: media_player.living_room_receiver
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: media_player.living_room_tv
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.ikea_outlet_2
    service: switch.turn_off

- alias: Turn on ambient lights when TV turns on
  trigger:
  - entity_id: media_player.living_room_receiver
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: media_player.living_room_tv
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.flex_strip_105

- alias: Turn off ambient lights when TV turns off
  trigger:
  - entity_id: media_player.living_room_receiver
    to: 'off'
    platform: state
    from: 'on'
    for:
      minutes: 1
  - entity_id: media_player.living_room_tv
    to: 'off'
    platform: state
    from: 'on'
    for:
      minutes: 1
  action:
  - service: light.turn_off
    entity_id: light.flex_strip_105

switch:
- platform: template
  switches:
    living_room_tv_power:
      value_template: "{{ is_state('media_player.living_room_tv', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.living_room_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.living_room_tv
      icon_template: >-
        {% if is_state('media_player.living_room_tv', 'on') %}
          mdi:television-classic
        {% else %}
          mdi:television-classic-off
        {% endif %}
    living_room_receiver_power:
      value_template: "{{ is_state('media_player.living_room_receiver', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.living_room_receiver
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.living_room_receiver
      icon_template: '{{ "mdi:set-top-box" }}'
