automation:
- alias: Turn off Air Purifier when TV turns on
  trigger:
  - entity_id: media_player.denon_avr_s640h
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: media_player.living_room_tv
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.ikea_outlet_2
    service: switch.turn_off

sensor:
- platform: template
  sensors:
    living_room_tv_volume:
      value_template: >
        {% if states("media_player.living_room_tv") == 'on' %}
          {{ state_attr('media_player.living_room_tv', 'volume_level') * 100 }}
        {% endif %}
