automation:
- alias: Turn On Man Cave Lights When Motion Detected
  trigger:
    platform: state
    entity_id: binary_sensor.hue_101_motion
    to: 'on'
  condition:
  - condition: template
    value_template: >
      {{ states("input_select.automation_mode") in ['home', 'guest'] }}
  action:
  - service: script.man_cave_auto_scene
  - service: automation.turn_off
    entity_id: automation.turn_on_man_cave_lights_when_motion_detected
  - service: rest_command.fire_tablet_701_brightness
    data:
      brightness: 255

- alias: Turn Off Man Cave Lights and Turn On Automation When No Motion
  trigger:
    platform: state
    entity_id: binary_sensor.hue_101_motion
    to: 'off'
    for:
      minutes: 30
  action:
  - service: homeassistant.turn_off
    entity_id: group.man_cave_lights
  - service: automation.turn_on
    entity_id: automation.turn_on_man_cave_lights_when_motion_detected
  - service: rest_command.fire_tablet_701_brightness
    data:
      brightness: 0

- alias: Turn Off Kitchen Lights And Tablet Screen When No Motion
  trigger:
    platform: state
    entity_id: binary_sensor.hue_100_motion
    to: 'off'
    for:
      minutes: 30
  action:
  - service: homeassistant.turn_off
    entity_id: group.kitchen_lights
  - service: light.turn_off
    entity_id: light.yoga_tablet_801_backlight

- alias: Turn On Kitchen Tablet Screen When Motion Detected
  trigger:
    platform: state
    entity_id: binary_sensor.hue_100_motion
    to: 'on'
  condition:
  - condition: template
    value_template: >
      {{ states("input_select.automation_mode") in ['home', 'guest'] }}
  action:
  - service: light.turn_on
    entity_id: light.yoga_tablet_801_backlight


- alias: Turn On Laundry Room Lights When Motion Detected
  trigger:
    platform: state
    entity_id: binary_sensor.smartthings_100_motion
    to: 'on'
  condition:
  - condition: template
    value_template: >
      {{ states("input_select.automation_mode") in ['home', 'guest'] }}
  action:
  - service: switch.turn_on
    entity_id: switch.laundry_room_light

- alias: Turn Off Laundry Room Lights When No Motion
  trigger:
    platform: state
    entity_id: binary_sensor.smartthings_100_motion
    to: 'off'
    for:
      seconds: 30
  action:
  - service: switch.turn_off
    entity_id: switch.laundry_room_light

- alias: Bedroom Motion - Home Mode
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '04:00:00'
    before: '08:00:00'
  - condition: state
    entity_id: input_select.automation_mode
    state: sleep
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.automation_mode
      option: home

sensor:
- platform: template
  sensors:
    hue_100_sensor_status:
      value_template: >
        {% if states("binary_sensor.hue_100_motion") not in ["off", "on"] %}
          Motion Unavailable
        {% elif states("sensor.hue_100_lux") == "unavailable" %}
          Lux Unavailable
        {% elif states("sensor.hue_100_temp") == "unavailable" %}
          Temp Unavailable
        {% elif states("sensor.hue_100_battery_level") == "unavailable" %}
          Battery Unavailable
        {% else %}
          OK
        {% endif %}
    hue_101_sensor_status:
      value_template: >
        {% if states("binary_sensor.hue_101_motion") not in ["off", "on"] %}
          Motion Unavailable
        {% elif states("sensor.hue_101_lux") == "unavailable" %}
          Lux Unavailable
        {% elif states("sensor.hue_101_temp") == "unavailable" %}
          Temp Unavailable
        {% elif states("sensor.hue_101_battery_level") == "unavailable" %}
          Battery Unavailable
        {% else %}
          OK
        {% endif %}
    smartthings_100_sensor_status:
      value_template: >
        {% if states("binary_sensor.smartthings_100_motion") not in ["off", "on"] %}
          Motion Unavailable
        {% elif states("sensor.smartthings_100_temp") == "unavailable" %}
          Temp Unavailable
        {% elif states("sensor.smartthings_100_battery_level") == "unavailable" %}
          Battery Unavailable
        {% else %}
          OK
        {% endif %}


homeassistant:
  customize:
    sensor.hue_100_sensor_status:
      templates:
        icon_color: >
          if (state === 'OK') return 'var(--primary-text-color)';
          else return 'var(--status-color-alert)';
    sensor.hue_101_sensor_status:
      templates:
        icon_color: >
          if (state === 'OK') return 'var(--primary-text-color)';
          else return 'var(--status-color-alert)';
    sensor.smartthings_100_sensor_status:
      templates:
        icon_color: >
          if (state === 'OK') return 'var(--primary-text-color)';
          else return 'var(--status-color-alert)';