automation:
- alias: Man Cave Motion - Turn on Lights
  trigger:
    platform: state
    entity_id: binary_sensor.man_cave_motion_sensor_hue
    to: 'on'
  action:
  - service: script.man_cave_auto_lights