pi_hole:
- host: '192.168.1.41'
  api_key: !secret pi_hole_api_key

switch:
- platform: template
  switches:
    pi_hole_enable_disable:
      value_template: "{{ is_state('sensor.pi_hole_status', 'enabled') }}"
      turn_on:
        service: pi_hole.enable
      turn_off:
        service: pi_hole.disable
        data:
          duration: '12:00:00'

sensor:
- platform: command_line
  name: Pi-hole Status
  scan_interval: 10
  command: !secret pi_hole_status_command
  value_template: >
    {{ value_json.status }}

- platform: template
  sensors:
    pi_hole_reachable:
      friendly_name: '192.168.1.41'
      value_template: >
        {% if is_state('device_tracker.pihole', 'home') %}
          Reachable
        {% else %}
          Not Reachable
        {% endif %}

homeassistant:
  customize:
    sensor.pi_hole_status:
      templates:
        icon_color: >
          if (state === 'enabled') return 'var(--secondary-text-color)';
          else return 'var(--primary-text-color)';
        icon: mdi:pi-hole
    sensor.pi_hole_reachable:
      templates:
        icon_color: >
          if (state === 'Reachable') return 'var(--secondary-text-color)';
          else return 'var(--primary-text-color)';
        icon: mdi:raspberry-pi;