scene:
- name: Man Cave Scene - Wake Up
  entities:
    light.flex_strip_101:
      state: on
      kelvin: 2000
      brightness: 255
    light.flex_strip_102:
      state: on
      kelvin: 2000
      brightness: 255
    light.hue_color_a19_101: off
    switch.ikea_smart_plug_101: off
- name: Man Cave Scene - Warm White
  entities:
    light.flex_strip_101:
      state: on
      kelvin: 3200
      brightness: 255
    light.flex_strip_102:
      state: on
      kelvin: 3200
      brightness: 255
    light.flex_strip_106:
      state: on
      kelvin: 3200
      brightness: 255
    light.hue_color_a19_101:
      state: on
      kelvin: 3200
      brightness: 255
    switch.ikea_smart_plug_101: on
- name: Man Cave Scene - Focus
  entities:
    light.flex_strip_101:
      state: on
      kelvin: 6500
      brightness: 255
    light.flex_strip_102:
      state: on
      kelvin: 6500
      brightness: 255
    light.flex_strip_106:
      state: on
      kelvin: 6500
      brightness: 255
    light.hue_color_a19_101:
      state: on
      kelvin: 6500
      brightness: 255
    switch.ikea_smart_plug_101: on
- name: Man Cave Scene - Reading Mode
  entities:
    light.flex_strip_101:
      state: on
      kelvin: 2000
      brightness: 100
    light.flex_strip_102: off
    light.flex_strip_106: off
    light.hue_color_a19_101:
      state: on
      kelvin: 2000
      brightness: 255
    switch.ikea_smart_plug_101: off
- name: Man Cave Scene - Sweet Tart
  entities:
    light.flex_strip_101:
      state: on
      hs_color: 
      - 314.824
      - 100
      brightness: 255
    light.hue_color_a19_101:
      state: on
      hs_color: 
      - 314.824
      - 100
      brightness: 255
    light.flex_strip_102:
      state: on
      hs_color: 
      - 195.178
      - 100
      brightness: 255
    light.flex_strip_106:
      state: on
      hs_color: 
      - 195.178
      - 100
      brightness: 255
- name: Man Cave Scene - Wind Down
  entities:
    light.flex_strip_101:
      state: on
      kelvin: 2000
      brightness: 255
    light.flex_strip_102:
      state: on
      kelvin: 2000
      brightness: 255
    light.flex_strip_106:
      state: on
      kelvin: 2000
      brightness: 255
    light.hue_color_a19_101: off

automation:
- alias: Man Cave Lights Disco Transition
  initial_state: 'off'
  trigger:
    platform: time_pattern
    seconds: '/5'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.flex_strip_101
      brightness: 255
      transition: 5
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"
  - service: light.turn_on
    data_template:
      entity_id: light.flex_strip_102
      brightness: 255
      transition: 5
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"
  - service: light.turn_on
    data_template:
      entity_id: light.hue_color_a19_101
      brightness: 255
      transition: 5
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"
  - service: light.turn_on
    data_template:
      entity_id: light.flex_strip_106
      brightness: 255
      transition: 5
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"

- alias: Man Cave Lights Shuffle Transition
  initial_state: 'off'
  trigger:
    platform: time_pattern
    seconds: '/30'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.flex_strip_101
      brightness: 255
      transition: 30
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"
  - service: light.turn_on
    data_template:
      entity_id: light.flex_strip_102
      brightness: 255
      transition: 30
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"
  - service: light.turn_on
    data_template:
      entity_id: light.flex_strip_106
      brightness: 255
      transition: 30
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"
  - service: light.turn_on
    data_template:
      entity_id: light.hue_color_a19_101
      brightness: 255
      transition: 30
      hs_color:
        - "{{ range(360)|random }}"
        - "{{ range(80,101)|random }}"

- alias: Turn Off Man Cave Shuffle When Scene Activated
  trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: scene
      service: turn_on
  condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.service_data.entity_id[:20] == "scene.man_cave_scene" }}
  action:
  - service: automation.turn_off
    entity_id:
    - automation.man_cave_lights_shuffle_transition
    - automation.man_cave_lights_disco_transition
