group:
  all_door_and_window_sensors:
    name: All Door and Window Sensors
    entities:
      - binary_sensor.front_door
      - binary_sensor.garage_entrance_door
      - binary_sensor.back_door
      - binary_sensor.garage_ext_door
      - binary_sensor.front_bedroom_window
      - binary_sensor.rear_bedroom_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.back_office_windows
      - binary_sensor.garage_windows
      - binary_sensor.kitchen_windows

input_boolean:
  bypass_open_sensors:
    name: Bypass Open Sensors
    icon: mdi:shield-check-outline

sensor:
- platform: template
  sensors:
    alarm_keypad_visible:
      friendly_name: Alarm Keypad Visible
      value_template: "{{ states('input_boolean.bypass_open_sensors') == 'on' or states('alarm_control_panel.home_alarm') != 'disarmed' or states('sensor.all_door_and_window_sensors') == 'off' }}"
      entity_id:
      - alarm_control_panel.home_alarm
      - sensor.all_door_and_window_sensors
      - input_boolean.bypass_open_sensors

    all_door_and_window_sensors:
      friendly_name: All Door and Window Sensors
      value_template: "{{ states('group.all_door_and_window_sensors') }}"
      entity_id:
      - binary_sensor.front_door
      - binary_sensor.garage_entrance_door
      - binary_sensor.back_door
      - binary_sensor.garage_ext_door
      - binary_sensor.front_bedroom_window
      - binary_sensor.rear_bedroom_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.back_office_windows
      - binary_sensor.garage_windows
      - binary_sensor.kitchen_windows

    open_doors_and_windows:
      friendly_name: Open Doors and Windows
      value_template: "{{ expand('group.all_door_and_window_sensors') | selectattr('state','eq','on') | map(attribute='name') | list | join(', ') | default('None', true) }}"
      entity_id:
      - binary_sensor.front_door
      - binary_sensor.garage_entrance_door
      - binary_sensor.back_door
      - binary_sensor.garage_ext_door
      - binary_sensor.front_bedroom_window
      - binary_sensor.rear_bedroom_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.back_office_windows
      - binary_sensor.garage_windows
      - binary_sensor.kitchen_windows

alarm_control_panel:
- platform: manual
  name: Home Alarm
  code: !secret alarm_code
  armed_home:
    arming_time: 0
  armed_night:
    arming_time: 0
  # delay_time: 10
  # trigger_time: 10