rest:
- authentication: basic
  username: !secret blueiris_user
  password: !secret blueiris_pass
  method: POST
  payload: '{"cmd": "cliplist", "camera": "annke101hd", "view": "all"}'
  scan_interval: 60
  resource: !secret blueiris_resource_url
  sensor:
  - name: "Driveway Alert Clips"
    value_template: "OK"
    json_attributes:
    - "data1"


group:
  all_door_and_window_sensors:
    name: All Door and Window Sensors
    entities:
      - binary_sensor.front_door
      - binary_sensor.garage_entrance_door
      - binary_sensor.back_door
      - binary_sensor.garage_ext_door
      - binary_sensor.front_bedroom_window
      - binary_sensor.rear_bedroom_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.back_office_windows
      - binary_sensor.garage_windows
      - binary_sensor.kitchen_windows

input_boolean:
  bypass_open_sensors:
    name: Bypass Open Sensors
    icon: mdi:shield-check-outline

binary_sensor:
- platform: ping
  host: 192.168.1.48
  count: 1
  scan_interval: 300
  name: Konnected 6-zone Alarm Panel
- platform: ping
  host: 192.168.1.47
  count: 1
  scan_interval: 300
  name: Konnected 6-zone Add-on Panel

sensor:
- platform: template
  sensors:
    alarm_keypad_visible:
      friendly_name: Alarm Keypad Visible
      value_template: "{{ states('input_boolean.bypass_open_sensors') == 'on' or states('alarm_control_panel.home_alarm') != 'disarmed' or states('sensor.all_door_and_window_sensors') == 'off' }}"
      entity_id:
      - alarm_control_panel.home_alarm
      - sensor.all_door_and_window_sensors
      - input_boolean.bypass_open_sensors

    all_door_and_window_sensors:
      friendly_name: All Door and Window Sensors
      value_template: "{{ states('group.all_door_and_window_sensors') }}"
      entity_id:
      - binary_sensor.front_door
      - binary_sensor.garage_entrance_door
      - binary_sensor.back_door
      - binary_sensor.garage_ext_door
      - binary_sensor.front_bedroom_window
      - binary_sensor.rear_bedroom_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.back_office_windows
      - binary_sensor.garage_windows
      - binary_sensor.kitchen_windows

    open_doors_and_windows:
      friendly_name: Open Doors and Windows
      value_template: "{{ expand('group.all_door_and_window_sensors') | selectattr('state','eq','on') | map(attribute='name') | list | join(', ') | default('None', true) }}"
      entity_id:
      - binary_sensor.front_door
      - binary_sensor.garage_entrance_door
      - binary_sensor.back_door
      - binary_sensor.garage_ext_door
      - binary_sensor.front_bedroom_window
      - binary_sensor.rear_bedroom_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.back_office_windows
      - binary_sensor.garage_windows
      - binary_sensor.kitchen_windows

alarm_control_panel:
- platform: manual
  name: Home Alarm
  code: !secret alarm_code
  armed_home:
    arming_time: 0
  armed_night:
    arming_time: 0

shell_command:
  save_doorbell_image: cp /config/www/images/ai_alerts/doorbell-person-hd.jpg /config/www/images/ai_alerts/doorbell-person-hd-latest.jpg

camera:
- platform: generic
  still_image_url: 'http://127.0.0.1:8123/local/images/ai_alerts/driveway-person-4k.jpg'
  name: Driveway Person Alert
- platform: generic
  still_image_url: 'http://127.0.0.1:8123/local/images/ai_alerts/doorbell-person-hd.jpg'
  name: Doorbell Person Alert
- platform: generic
  still_image_url: 'http://127.0.0.1:8123/local/images/ai_alerts/driveway-vehicle-4k.jpg'
  name: Driveway Car Alert
- platform: generic
  still_image_url: 'http://127.0.0.1:8123/local/images/ai_alerts/doorbell-person-hd-latest.jpg'
  name: Doorbell Person Alert Latest
- platform: generic
  still_image_url: 'http://127.0.0.1:8123/local/images/doorbell-press-alert.jpg'
  name: Doorbell Press Alert Latest
- platform: generic
  still_image_url: 'http://127.0.0.1:8123/local/images/ai_alerts/great-room-person.jpg'
  name: Great Room Person Alert
- platform: generic
  still_image_url: >
    {% if (states.binary_sensor.ai_driveway_person_occupancy.last_changed < states.binary_sensor.ai_driveway_car_motion.last_changed) %}
      http://127.0.0.1:8123/local/images/ai_alerts/driveway-vehicle-4k.jpg
    {% else %}
      http://127.0.0.1:8123/local/images/ai_alerts/driveway-person-4k.jpg
    {% endif %}
  name: Driveway Last Alert
- platform: generic
  still_image_url: 'http://127.0.0.1:8123/local/images/ai_alerts/garage-person.jpg'
  name: Garage Person Alert

folder_watcher:
- folder: /config/www/images/ai_alerts
  patterns:
  - '*.jpg'