###################################################################
#
# Tasker
# ------
#
#   This package contains configuration for automation using the
#   Android Tasker app.
#
# Features
# --------
# 
#  * Set house to sleep mode when phone placed face-down at night
#
###################################################################

input_boolean:
  tasker_phone_orientation:
      name: Phone Orientation (Tasker)
      icon: mdi:cellphone-android

automation:
- alias: Phone Orientation Down - Sleep Mode
  trigger:
  - platform: state
    entity_id: input_boolean.tasker_phone_orientation
    to: 'on'
    for: 00:05:00
  condition:
  - condition: state
    entity_id: person.andrew
    state: home
  - condition: template
    value_template: '{{ states("input_select.automation_mode") in ["home"] }}'
  - condition: time
    after: '21:00:00'
    before: '02:00:00'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.automation_mode
      option: sleep