ecobee:
  api_key: !secret ecobee_api_key

script:
  set_climate_away_mode:
    alias: Set Climate Away Mode
    sequence:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.thermostat
        preset_mode: away

  resume_climate_schedule:
    alias: Resume Climate Schedule
    sequence:
    - service: ecobee.resume_program
      data:
        entity_id: climate.thermostat
        resume_all: true
  
  set_climate_kaitlyn_away_mode:
    alias: Set Climate Kaitlyn Away Mode
    sequence:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.thermostat
        preset_mode: Kaitlyn Away

sensor:
- platform: template
  sensors:
    target_temperature:
      value_template: '{{ state_attr("climate.thermostat", "temperature") }}'