sensor:
- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
  monitored_conditions:
    - icon
    - summary
    - temperature
    - apparent_temperature
    - precip_probability
    - temperature_high
    - temperature_low
    - daily_summary
  scan_interval:
    minutes: 5

- platform: template
  sensors:
    dark_sky_current_text:
      value_template: >
        {% if is_state("sensor.dark_sky_icon","clear-day") %} Clear 
        {% elif is_state("sensor.dark_sky_icon","clear-night") %} Clear 
        {% elif is_state("sensor.dark_sky_icon","rain") %} Rain
        {% elif is_state("sensor.dark_sky_icon","snow") %} Snowy
        {% elif is_state("sensor.dark_sky_icon","fog") %} Foggy
        {% elif is_state("sensor.dark_sky_icon","sleet") %} Sleet
        {% elif is_state("sensor.dark_sky_icon","wind") %} Windy
        {% elif is_state("sensor.dark_sky_icon","cloudy") %} Cloudy
        {% elif is_state("sensor.dark_sky_icon","partly-cloudy-day") %} Partly Cloudy
        {% elif is_state("sensor.dark_sky_icon","partly-cloudy-night") %} Partly Cloudy
        {% elif is_state("sensor.dark_sky_icon","hail") %} Hailing
        {% elif is_state("sensor.dark_sky_icon","lightning") %} Lightning
        {% elif is_state("sensor.dark_sky_icon","thunderstorm") %} Thunderstorm
        {% endif %}

input_text:
  dark_sky_daily_summary:
    name: Daily Temperature Sim
    initial: Rain tomorrow through next Wednesday.