weather:
- platform: openweathermap
  api_key: !secret open_weather_api_key
  mode: freedaily

sensor:
- platform: openweathermap
  api_key: !secret open_weather_api_key
  monitored_conditions:
  - temperature

input_text:
  dark_sky_daily_summary:
    name: Daily Temperature Sim
    initial: Rain tomorrow through next Wednesday.